// Mocks generated by Mockito 5.4.4 from annotations
// in nasa_today/test/app/domain/usecases/get_astronomy_picture_of_the_day_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa_today/app/domain/entities/entities.dart' as _i2;
import 'package:nasa_today/app/domain/repositories/get_astronomy_picture_of_the_day_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAstronomyPictureEntity_0 extends _i1.SmartFake
    implements _i2.AstronomyPictureEntity {
  _FakeAstronomyPictureEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IGetAstronomyPictureOfTheDayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetAstronomyPictureOfTheDayRepository extends _i1.Mock
    implements _i3.IGetAstronomyPictureOfTheDayRepository {
  MockIGetAstronomyPictureOfTheDayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AstronomyPictureEntity> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.AstronomyPictureEntity>.value(
            _FakeAstronomyPictureEntity_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AstronomyPictureEntity>);
}
