name: test-my-app

on:
  push:
    branches: 'ci/cd'

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check Flutter SDK version
        run: flutter doctor -v
          
      - run: flutter pub get
      - run: flutter test