name: nasa-today-tests

on:
  push:
    branches: 'main'
  pull_request:
    types:
      - opened
    branches: 'main'

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check Flutter SDK version
        run: flutter doctor -v
          
      - name: Get app dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage